# 構築されるURL
base_url = "https://blog.lino.blue/"

# タイトル
title = "blog.lino.blue"

# デフォルトの言語。  フィードで使用されます。
default_language = "ja"

# 「true」に設定すると、生成された HTML ファイルが縮小されます。
minify_html = true

# 「true」に設定すると、フィードが自動的に生成されます。
generate_feed = true

# 使用するサイトのテーマ
theme = "anemone"

# sass ディレクトリ内のすべての Sass ファイルを自動的にコンパイルするかどうか
compile_sass=true

# JavaScript ライブラリによって後で使用される検索インデックスを構築するかどうか
build_search_index = false

# サイトに対してレンダリングされる分類法とデフォルトの構成
taxonomies = [
    {name = "tags", feed = true},
]


[markdown]
highlight_theme = "gruvbox-dark"
render_emoji = true
external_links_target_blank = true
smart_punctuation = true
highlight_code = true

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[link_checker]
internal_level = "warn"

[extra]
author="aosjmi"
display_author = false

full_width = true
favicon = "/favicon.ico"

header_nav = [
	{url = "/", name_ja = "home" } ,
	{url = "/posts", name_ja = "posts" },
        {url = "https://cloud.umami.is/share/Z1fvDYfyU4vrKhpv/blog.lino.blue", name_ja = "analytics" },
       
]
list_pages = false
twitter_card = false

enable_katex = true
disqus = { enabled=false, short_name="donalog" }
